# Generated by Django 5.1.15 on 2026-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('voice', 'Voice'), ('video_note', 'Video note'), ('file', 'File')], default='text', max_length=16),
        ),
    ]
