# Generated by Django 5.1.15 on 2026-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='achieved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='achievement_media',
            field=models.FileField(blank=True, null=True, upload_to='achievements/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='dream',
            name='achievement_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
