# Generated by Django 5.1.15 on 2026-07-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_dream_achieved_date_dream_achievement_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dreams/%Y/%m/')),
                ('kind', models.CharField(default='image', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dreams.dream')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
